# combine_params.sh: to define RepExpress env variables
# for combining GENLOC files generated by map_count_reads.sh
# runs.
#
# Variables that are consistent across a series of runs
# are already defined in basic_params.sh
# 
# Edit this to reflect the parameters required for each combine run.

# the output directory for the combine: leave blank for
# output into the current directory.

combine_output_dir="./combined_out/";

# We need to define the source files, either the original
# fastq files or the derived genloc output files from map_count_reads.
# At least one of these should be set to the name of such a file.


fastq_name_file="";

genloc_name_file="./genloc_file_list.txt";

# if fastq files are specified (fastq_name_file is used)
# we need to specify where the resulting genloc files are,
# noting that they will all need to be in the same directory.
# leave this blank if genloc_name_file is used or if all
# generated genloc files are in the current directory

genloc_file_dir="";
